# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  displayName: 'Create WAR file'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  displayName: 'Build and push image to acr'
  inputs:
    containerRegistry: 'fonacregistry'
    repository: '$(imageName):$(version)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags:
- task: CmdLine@2
  displayName: 'Replace version number'
  inputs:
    script: 'sed -i ''s/bprestws:latest/$(imageName):$(version)/g'' create-service-manifest.yaml' 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'create-service-manifest.yaml'
    ArtifactName: 'YAML'
    publishLocation: 'Container'